### ISSUE TITLE
"autosize": true in chart options not work

### ISSUE THREAD

**Issue by a-aslani** [volkanakkus/nuxt-tradingview#2]
Hello
It is necessary to use this option to fill the height space, but this option does not work in this module

**Comment by volkanakkus** [comment]
Hi @a-aslani , 

You have noticed an important bug. We should release a patch for this within the day

**Comment by volkanakkus** [comment]
@a-aslani 

With the new patch (v1.3.1), we've fixed this issue. According to the TradingView documentation, if you enable autosize, it automatically adds width and height set to 100% to the provided options (meaning autosize cannot be used without width and height set to 100%).

<img width="649" alt="image" src="https://github.com/volkanakkus/nuxt-tradingview/assets/8204111/65dbb6d2-f8e0-4eaa-9e8b-9319ec85a584">


However, with the new patch, we no longer need this also. You can simply use `autosize: true` as shown below, and the module will automatically set height and width to 100%."

```html
<MiniChart
  :options="{
    autosize: true,
    // width: '100%',
    // height: '100%',

    // no need for width and height anymore if autosize true 
  }" />
```
