### ISSUE TITLE
It's possible to use option "custom_indicators_getter"?

### ISSUE THREAD

**Issue by digoburigo** [volkanakkus/nuxt-tradingview#4]
I want to know if it's possible to use `custom_indicators_getter` property to use a custom indicator?
I want to know too how to use the `studies_overrides` too it it's possible

**Comment by volkanakkus** [comment]
Hi,
There might be a misunderstanding; the `custom_indicators_getter` and `studies_overrides` keys you mentioned are properties provided by the Charting Library offered by TradingView.

This library is here: https://www.tradingview.com/charting-library-docs/

On the other hand, this Nuxt Module contains TradingView Widgets, which are different from the Charting Library. The documentation for this can be found here: https://www.tradingview.com/widget-docs/widgets/charts/advanced-chart/

Therefore, this module only includes widgets provided by TradingView. We don't have a fully customizable Charting Library. While that library allows you to create custom charts, this module and widget library allow us to use TradingView widgets with our own options.

So, the question you asked is not something present in this module, but within the TradingView Widgets, you can select TradingView's provided indicators within the Chart Widget as shown below:

<img width="1127" alt="image" src="https://github.com/volkanakkus/nuxt-tradingview/assets/8204111/33bfdf9e-57b7-4920-8c14-86581efc84e6">
